name: ros-talker-listener
base: core18
version: "0.1"
summary: ROS Talker/Listener Example
description: |
  This example requires roscore as well as a talker and listener.

grade: devel
confinement: devmode

parts:
  ros-tutorials:
    plugin: catkin
    source: https://github.com/ros/ros_tutorials.git
    source-branch: melodic-devel
    source-space: roscpp_tutorials/

apps:
  run:
    command: roslaunch roscpp_tutorials talker_listener.launch
